# Generated by Django 5.1.4 on 2025-01-12 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aboutText', models.TextField(default='DefaultValue', null=True)),
                ('aboutFile', models.ImageField(null=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contactName', models.CharField(default='DefaultValue', max_length=100, null=True)),
                ('contactAdress', models.TextField(default='DefaultValue', null=True)),
                ('contactTel', models.CharField(default='DefaultValue', max_length=150, null=True)),
                ('contactFaks', models.CharField(default='DefaultValue', max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContactFormSocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contactİnst', models.CharField(default='DefaultValue', max_length=150, null=True)),
                ('contactLinke', models.CharField(default='DefaultValue', max_length=150, null=True)),
                ('contactFace', models.CharField(default='DefaultValue', max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GalleryForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fotoName', models.CharField(default='DefaultValue', max_length=100, null=True)),
                ('statementWeb', models.TextField(default='DefaultValue', null=True)),
                ('fotoFile', models.ImageField(null=True, upload_to='images/')),
                ('optionWeb', models.CharField(default='DefaultValue', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HomepageContentForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mainText', models.CharField(default='DefaultValue', max_length=200, null=True)),
                ('mainDescText', models.TextField(default='DefaultValue', null=True)),
                ('anaSayfaFoto', models.ImageField(null=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='PersonnelForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personelName', models.CharField(max_length=20)),
                ('personelDesc', models.TextField(default='DefaultValue', null=True)),
                ('personelFoto', models.ImageField(null=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='ReferenceForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referansName', models.CharField(default='DefaultValue', max_length=100, null=True)),
                ('referansUrl', models.CharField(default='DefaultValue', max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serviceName', models.CharField(default='DefaultValue', max_length=100, null=True)),
                ('serviceFoto', models.ImageField(null=True, upload_to='images/')),
                ('serviceDesc', models.TextField(default='DefaultValue', null=True)),
            ],
        ),
    ]
