# Generated by Django 5.1.4 on 2025-01-12 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsDashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomepageFotoForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anaSayfaFoto', models.ImageField(null=True, upload_to='images/')),
            ],
        ),
        migrations.RemoveField(
            model_name='homepagecontentform',
            name='anaSayfaFoto',
        ),
    ]
