# Generated by Django 5.1.4 on 2025-01-10 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmsDashboard', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Common_database',
        ),
    ]
