# Generated by Django 5.1.4 on 2025-01-13 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsDashboard', '0002_homepagefotoform_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactformsocialmedia',
            name='contactİnst',
        ),
        migrations.AddField(
            model_name='contactformsocialmedia',
            name='contactInst',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='contactformsocialmedia',
            name='contactFace',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='contactformsocialmedia',
            name='contactLinke',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
