# Generated by Django 5.1.4 on 2025-01-10 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cmsDashboard', '0002_delete_common_database'),
    ]

    operations = [
        migrations.CreateModel(
            name='database_form_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formType', models.CharField(max_length=100)),
                ('fotoName', models.CharField(default='DefaultValue', max_length=100, null=True)),
                ('statementWeb', models.TextField(default='DefaultValue', null=True)),
                ('fotoFile', models.ImageField(null=True, upload_to='images')),
                ('optionWeb', models.CharField(default='DefaultValue', max_length=100, null=True)),
                ('mainText', models.CharField(default='DefaultValue', max_length=200, null=True)),
                ('mainDescText', models.TextField(default='DefaultValue', null=True)),
                ('anaSayfaFoto', models.ImageField(null=True, upload_to='images')),
                ('personelName', models.CharField(max_length=20)),
                ('personelDesc', models.TextField(default='DefaultValue', null=True)),
                ('personelFoto', models.ImageField(null=True, upload_to='images')),
                ('aboutText', models.TextField(default='DefaultValue', null=True)),
                ('aboutFile', models.ImageField(null=True, upload_to='images')),
                ('referansName', models.CharField(default='DefaultValue', max_length=100, null=True)),
                ('referansUrl', models.CharField(default='DefaultValue', max_length=150, null=True)),
                ('serviceName', models.CharField(default='DefaultValue', max_length=100, null=True)),
                ('serviceFoto', models.ImageField(null=True, upload_to='images')),
                ('serviceDesc', models.TextField(default='DefaultValue', null=True)),
                ('contactName', models.CharField(default='DefaultValue', max_length=100, null=True)),
                ('contactAdress', models.TextField(default='DefaultValue', null=True)),
                ('contactTel', models.CharField(default='DefaultValue', max_length=150, null=True)),
                ('contactFaks', models.CharField(default='DefaultValue', max_length=150, null=True)),
                ('contactİnst', models.CharField(default='DefaultValue', max_length=150, null=True)),
                ('contactLinke', models.CharField(default='DefaultValue', max_length=150, null=True)),
                ('contactFace', models.CharField(default='DefaultValue', max_length=150, null=True)),
            ],
        ),
    ]
