# Generated by Django 5.1.4 on 2025-01-13 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmsDashboard', '0003_remove_contactformsocialmedia_contacti_nst_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactformsocialmedia',
            old_name='contactInst',
            new_name='contactİnst',
        ),
    ]
